//! Built-in structure definitions compiled into the library.
//!
//! All `.ksy` files from `data/structures/` are discovered by `build.rs` at
//! compile time and embedded via `include_str!`. Adding or removing `.ksy`
//! files requires no source changes — the build script picks them up
//! automatically.
//!
//! File-based definitions from search paths and the `OSML_IO_STRUCTURE_PATH`
//! environment variable take priority over built-ins, allowing users to
//! override or extend definitions without recompiling.

// Generated by build.rs: an array of (name, yaml_content) pairs.
include!(concat!(env!("OUT_DIR"), "/builtin_definitions.rs"));

/// Returns the compiled-in `(name, yaml)` pairs for all built-in definitions.
pub(crate) fn builtin_definitions() -> &'static [(&'static str, &'static str)] {
    BUILTIN_KSY
}
